import { faker } from "@faker-js/faker";

export const professionalsMock = [
  {
    id: faker.database.mongodbObjectId,
    name: faker.name.fullName(),
    cellphone: faker.phone.number("(##) #####-####"),
    email: faker.internet.email(),
    profilePicture: faker.image.avatar(),
    jobTitle: faker.lorem.word(),
    description: faker.lorem.paragraph(),
    specialities: Array(5).fill(faker.lorem.word()),
    hourRate: faker.commerce.price(),
  },
  {
    id: faker.database.mongodbObjectId,
    name: faker.name.fullName(),
    cellphone: faker.phone.number("(##) #####-####"),
    email: faker.internet.email(),
    profilePicture: faker.image.avatar(),
    jobTitle: faker.lorem.word(),
    description: faker.lorem.paragraph(),
    specialities: Array(5).fill(faker.lorem.word()),
    hourRate: faker.commerce.price(),
  },
  {
    id: faker.database.mongodbObjectId,
    name: faker.name.fullName(),
    cellphone: faker.phone.number("(##) #####-####"),
    email: faker.internet.email(),
    profilePicture: faker.image.avatar(),
    jobTitle: faker.lorem.word(),
    description: faker.lorem.paragraph(),
    specialities: Array(5).fill(faker.lorem.word()),
    hourRate: faker.commerce.price(),
  },
  {
    id: faker.database.mongodbObjectId,
    name: faker.name.fullName(),
    cellphone: faker.phone.number("(##) #####-####"),
    email: faker.internet.email(),
    profilePicture: faker.image.avatar(),
    jobTitle: faker.lorem.word(),
    description: faker.lorem.paragraph(),
    specialities: Array(5).fill(faker.lorem.word()),
    hourRate: faker.commerce.price(),
  },
  {
    id: faker.database.mongodbObjectId,
    name: faker.name.fullName(),
    cellphone: faker.phone.number("(##) #####-####"),
    email: faker.internet.email(),
    profilePicture: faker.image.avatar(),
    jobTitle: faker.lorem.word(),
    description: faker.lorem.paragraph(),
    specialities: Array(5).fill(faker.lorem.word()),
    hourRate: faker.commerce.price(),
  },
  {
    id: faker.database.mongodbObjectId,
    name: faker.name.fullName(),
    cellphone: faker.phone.number("(##) #####-####"),
    email: faker.internet.email(),
    profilePicture: faker.image.avatar(),
    jobTitle: faker.lorem.word(),
    description: faker.lorem.paragraph(),
    specialities: Array(5).fill(faker.lorem.word()),
    hourRate: faker.commerce.price(),
  },
  {
    id: faker.database.mongodbObjectId,
    name: faker.name.fullName(),
    cellphone: faker.phone.number("(##) #####-####"),
    email: faker.internet.email(),
    profilePicture: faker.image.avatar(),
    jobTitle: faker.lorem.word(),
    description: faker.lorem.paragraph(),
    specialities: Array(5).fill(faker.lorem.word()),
    hourRate: faker.commerce.price(),
  },
  {
    id: faker.database.mongodbObjectId,
    name: faker.name.fullName(),
    cellphone: faker.phone.number("(##) #####-####"),
    email: faker.internet.email(),
    profilePicture: faker.image.avatar(),
    jobTitle: faker.lorem.word(),
    description: faker.lorem.paragraph(),
    specialities: Array(5).fill(faker.lorem.word()),
    hourRate: faker.commerce.price(),
  },
  {
    id: faker.database.mongodbObjectId,
    name: faker.name.fullName(),
    cellphone: faker.phone.number("(##) #####-####"),
    email: faker.internet.email(),
    profilePicture: faker.image.avatar(),
    jobTitle: faker.lorem.word(),
    description: faker.lorem.paragraph(),
    specialities: Array(5).fill(faker.lorem.word()),
    hourRate: faker.commerce.price(),
  },
  {
    id: faker.database.mongodbObjectId,
    name: faker.name.fullName(),
    cellphone: faker.phone.number("(##) #####-####"),
    email: faker.internet.email(),
    profilePicture: faker.image.avatar(),
    jobTitle: faker.lorem.word(),
    description: faker.lorem.paragraph(),
    specialities: Array(5).fill(faker.lorem.word()),
    hourRate: faker.commerce.price(),
  },
];
