export const initialValues = {
  name: "",
  email: "",
  password: "",
  confirmPassword: "",
  cpf: "",
  cellphone: "",
  birthDate: null,
  profilePicture: "",
  jobTitle: "",
  description: "",
  specialities: [],
  hourRate: null,
  cfp: "",
};
